# Generated by Django 3.1.2 on 2020-10-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='motive',
            field=models.TextField(blank=True, null=True, verbose_name='motivo da pendência'),
        ),
    ]
