# Generated by Django 3.1.2 on 2020-10-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='motive',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='motivo da pendência'),
        ),
    ]
