# Generated by Django 3.1.2 on 2020-10-15 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201014_2249'),
        ('food', '0003_auto_20201012_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='registered_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.servant', verbose_name='usuário que cadastrou'),
        ),
    ]
