# Generated by Django 3.1.2 on 2020-10-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='usuário (matricula para alunos e SUAP para servidores)'),
        ),
    ]
