# Generated by Django 3.1.2 on 2020-10-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profilepic',
        ),
        migrations.AddField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='foto'),
        ),
    ]
