# Generated by Django 3.1.2 on 2020-10-15 01:49

import dining_hall.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201013_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to=dining_hall.accounts.models.profilepic_directory_path, verbose_name='foto'),
        ),
    ]
