# Generated by Django 3.1.2 on 2020-10-05 01:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id do curso')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id da turma')),
                ('shift', models.CharField(choices=[('matutino', 'matutino'), ('vespertino', 'vespertino'), ('noturno', 'noturno')], max_length=10, verbose_name='turno')),
                ('description', models.CharField(max_length=55, verbose_name='descrição')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.course', verbose_name='curso')),
            ],
            options={
                'verbose_name': 'turma',
                'verbose_name_plural': 'turmas',
            },
        ),
    ]
